
version: '3.9'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MODEL_NAME=${MODEL_NAME:-distilbert-base-uncased-finetuned-sst-2-english}
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
